### ISSUE TITLE
lib/tasks/dev.rake trying to load rspec/core on deploy

### ISSUE THREAD

**Issue by hackmastera** [chemheritage/chf-sufia#379]
We need to keep this file from loading in a production environment.

```
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host staging: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
LoadError: cannot load such file -- rspec/core
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/sufia-project/releases/20170309153419/lib/tasks/dev.rake:1:in `<top (required)>'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `each'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/opt/sufia-project/releases/20170309153419/Rakefile:6:in `<top (required)>'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by jrochkind** [comment]
Not there yet. 

~~~
Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host staging: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
LoadError: cannot load such file -- solr_wrapper
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/sufia-project/releases/20170309161219/lib/tasks/dev.rake:3:in `<top (required)>'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `each'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/opt/sufia-project/releases/20170309161219/Rakefile:6:in `<top (required)>'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:22:in `load'
/usr/local/bin/bundle:22:in `<main>
~~~
