### ISSUE TITLE
RIIIF object display error

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#660]
Using the RIIIF branch, trying to view an object generates the following error
```F, [2017-06-28T16:59:51.330262 #3076] FATAL -- : 
ActionView::Template::Error (both URI are relative):
    34:     </li>
    35:     <li>
    36:       <%= link_to("Full-size JPEG",
    37:                   (member ? riiif_image_url(member.riiif_file_id, format: "jpg", size: "full") : "#"),
    38:                   target: "_new",
    39:                   data: {
    40:                     content_hook: "dl-jpeg-link",
  app/helpers/riiif_helper.rb:27:in `riiif_image_url'
  app/views/curation_concerns/base/_chf_download_menu.html.erb:37:in `_app_views_curation_concerns_base__chf_download_menu_html_erb___447489976140905712_94989900'
  app/views/curation_concerns/base/_show_page_image.html.erb:50:in `block in _app_views_curation_concerns_base__show_page_image_html_erb___324030783889583127_97190000'
  app/views/curation_concerns/base/_show_page_image.html.erb:3:in `_app_views_curation_concerns_base__show_page_image_html_erb___324030783889583127_97190000'
  app/helpers/curation_concerns_helper.rb:9:in `show_page_representative_media'
  app/views/curation_concerns/base/show.html.erb:28:in `_app_views_curation_concerns_base_show_html_erb___1034874097241507161_97804160'
```

**Comment by hackmastera** [comment]
I think this is resolved. @sanfordd? please close if yes, thanks!
