### ISSUE TITLE
DZI lazy error

### ISSUE THREAD

**Issue by sanfordd** [chemheritage/chf-sufia#852]
I suspect this is unrelated to #851 

When running `rake chf:dzi:push_all[lazy]` it gave an error related to the gemfile error
`Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile require
s rake 12.0.0. Prepending bundle exec to your command may solve this.`
Using `bundle exec ` caused the following error

```rake aborted!
LoadError: cannot load such file -- solr_wrapper
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/opt/sufia-project/releases/20170905185959/lib/tasks/dev.rake:6:in `<top (required)>'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `block in run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `each'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:658:in `run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:452:in `run_tasks_blocks'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:453:in `load_tasks'
/opt/sufia-project/releases/20170905185959/Rakefile:6:in `<top (required)>'
/opt/sufia-project/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

**Comment by catlu** [comment]
For work: https://digital.chemheritage.org/concern/generic_works/rx913q529--

Fileset without thumbnail and DZI: https://digital.chemheritage.org/concern/parent/rx913q529/file_sets/n296wz608

Child work without thumbnail and DZI:
https://digital.chemheritage.org/concern/generic_works/bg257f64n

Child work without thumbnail only: 
https://digital.chemheritage.org/concern/generic_works/vm40xs12q

**Comment by jrochkind** [comment]
@sanfordd can you still reproduce this? I can not.
